### ISSUE TITLE
GSOC'22 PROJECT DISCUSSION

### ISSUE THREAD

**Issue by Nageshbansal** [weecology/neonVstAop#5]
@MarconiS, In retrieve_aop_data, is this data argument contains VST data information i.e information for specific site and month of a vegetation structure.
https://github.com/weecology/neonVegWrangleR/blob/72586ce699385a993961837abf4d391b7b70d70a/R/retrieve_aop_data.R#L11

**Comment by MarconiS** [comment]
correct. `data` refers to the vegetation structure or a dataframe containing `plotID`, `siteID`, `year`, `utmZone`, and area of interest geolocation i.e. `easting`, `northing`.

Note that the previous naming of plotEasting and plotNorthing has been changed in easting and northing. I've pushed the updated colnames for consistency.

**Comment by Nageshbansal** [comment]
@MarconiS, at line 44 https://github.com/weecology/neonVegWrangleR/blob/c34c1083b18a5aa6f0d9d72d16a51f4f6eaee0bf/R/retrieve_coords_itc.R#L44
we're selecting easting and northing from argument dat ( which is vst_mappingandtagging) right?
But the vst_mappingandtagging doesn't contain any column like easting and northing.

**Comment by Nageshbansal** [comment]
Hi @henrykironde @MarconiS, I have finished writing my proposal for the NeonVegWrangler project. Can I share it with you over mail or dm for a review/feedback? I'll be extremely grateful.

**Comment by henrykironde** [comment]
Share as a a google doc

**Comment by Nageshbansal** [comment]
Sure, please check your gitter
